### PR TITLE
Update list.json

### PR DESCRIPTION
**Pull request by zcore-dev**
Add PackageInfo and RealtimeHTML plugin's to Graviton.

### CODE REVIEW

**Comment by marc2332** [comment]
Looks good!

But, there is a little problem: modyfing the DOM directly could cause future problems, so, my solution is to instead of creating the frameset element inside of #content_app you could create a tab of type free on a new screen, and there put your frameset element. And if it goes well I will accept it. 

To create an splitted screen:
https://github.com/Graviton-Code-Editor/Graviton-App/wiki/API#add

To create a tab: 
https://github.com/Graviton-Code-Editor/Graviton-App/wiki/API#tabs

I hope you understand 😄 

If you need more help you can contact me on the discord server: https://discord.gg/gg6CTYA

**Comment by zcore-dev** [comment]
1. Removed DOM from RealtimeHTML
2. Frameset's are not working/allowed?, so i had to add the HTML directly in tab content.

If there's anything else please let me know. :)

**Comment by marc2332** [comment]
The thing I want to avoid is to append HTML elements whatever the dev wants. So, a solution is to use the default Components, as tabs, windows, dialogs... 

In your case the best would be a Tab on a different screen. You can put your frameset in the data property while creating the tab

**Comment by zcore-dev** [comment]
Thanks,

Moved to iframe now, please check it out.
Frameset+Frame are blocked by some filter, so it'll be iframe anyway.

**Comment by marc2332** [comment]
I have tested it, opening it in a different screen and then trying to modify the html bugs it (Graviton fault, not yours) But doing it on the same screen works perfect 😄 

Could you remove the part on the readme where you say it also works on a different screen? 

thanks

I will test it more as soon as possible

Good job

**Comment by zcore-dev** [comment]
Done,

Now it follows the selected file screen.

**Comment by marc2332** [comment]
I am searching for people to test it on my Discord server, I but nobody wants D:

**Pull request closed without merging**
